import {NextPage} from 'next';
import styles from '../../styles/Home.module.css';
import Head from 'next/head';

const Secret: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Secret</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                これは秘密の情報だ！絶対に漏れてはイケナイ！
            </main>

        </div>
    )
}
export default Secret